using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using Amanotes.Core;

namespace Amanotes.Core.Editor
{
    [CustomEditor(typeof(ObjectPoolManager))]
    public class ObjectPoolEditor : UnityEditor.Editor
    {
        private const string ENUM_SCRIPT_PATH = "Assets/Framework/Managers/PoolingObject/PoolName.cs";

        public override void OnInspectorGUI()
        {
            ObjectPoolManager manager = (ObjectPoolManager)target;

            EditorGUILayout.Space(10);
            EditorGUILayout.LabelField("Object Pool Manager", EditorStyles.boldLabel);
            EditorGUILayout.Space(5);

            // Settings
            EditorGUILayout.BeginVertical("box");
            EditorGUILayout.LabelField("Settings", EditorStyles.boldLabel);

            manager.usePositionInsteadOfDeactivate = EditorGUILayout.Toggle(
                new GUIContent("Use Position Instead Of Deactivate",
                "Move object instead of SetActive(false)"),
                manager.usePositionInsteadOfDeactivate
            );

            if (manager.usePositionInsteadOfDeactivate)
            {
                manager.returnPosition = EditorGUILayout.Vector3Field(
                    new GUIContent("Return Position", "Position to move object when returned"),
                    manager.returnPosition
                );
            }

            EditorGUILayout.EndVertical();
            EditorGUILayout.Space(10);

            // Pool List
            EditorGUILayout.BeginVertical("box");
            EditorGUILayout.LabelField("Pool List", EditorStyles.boldLabel);
            EditorGUILayout.Space(5);
            DrawDefaultInspector();
            EditorGUILayout.EndVertical();

            EditorGUILayout.Space(10);

            // Buttons
            EditorGUILayout.BeginVertical("box");
            EditorGUILayout.LabelField("Actions", EditorStyles.boldLabel);
            EditorGUILayout.Space(5);

            GUI.backgroundColor = Color.green;
            if (GUILayout.Button("Generate PoolName Enum", GUILayout.Height(40)))
                GeneratePoolNameEnum(manager);
            GUI.backgroundColor = Color.white;

            EditorGUILayout.Space(5);

            GUI.backgroundColor = Color.red;
            if (GUILayout.Button("Clear All Pools", GUILayout.Height(35)))
            {
                if (EditorUtility.DisplayDialog("Clear All Pools",
                    "Are you sure you want to clear all pools?\nThis action cannot be undone!",
                    "Yes, Clear All", "Cancel"))
                {
                    manager.ClearAllPools();
                }
            }
            GUI.backgroundColor = Color.white;

            EditorGUILayout.EndVertical();

            // Pool Statistics
            if (Application.isPlaying)
            {
                EditorGUILayout.Space(10);
                EditorGUILayout.BeginVertical("box");
                EditorGUILayout.LabelField("Runtime Statistics", EditorStyles.boldLabel);

                foreach (var poolData in manager.poolDataList)
                {
                    if (System.Enum.TryParse<PoolName>(poolData.poolName, out var poolEnum))
                    {
                        int count = manager.GetPoolCount(poolEnum);
                        EditorGUILayout.LabelField($"{poolData.poolName}: {count} available");
                    }
                }

                EditorGUILayout.EndVertical();
                Repaint();
            }

            if (GUI.changed)
                EditorUtility.SetDirty(manager);
        }

        private void GeneratePoolNameEnum(ObjectPoolManager manager)
        {
            if (manager.poolDataList.Count == 0)
            {
                EditorUtility.DisplayDialog("Cannot Generate Enum",
                    "Pool list is empty! Please add at least one pool.", "OK");
                return;
            }

            string directory = Path.GetDirectoryName(ENUM_SCRIPT_PATH);
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by ObjectPoolEditor");
            sb.AppendLine("// DO NOT EDIT THIS FILE MANUALLY!");
            sb.AppendLine($"// Generated at: {System.DateTime.Now}");
            sb.AppendLine();
            sb.AppendLine("public enum PoolName");
            sb.AppendLine("{");

            for (int i = 0; i < manager.poolDataList.Count; i++)
            {
                var poolData = manager.poolDataList[i];

                if (string.IsNullOrEmpty(poolData.poolName))
                    poolData.poolName = poolData.prefab != null ? poolData.prefab.name : $"Pool_{i}";

                string enumName = SanitizeEnumName(poolData.poolName);
                sb.AppendLine($"    {enumName},");
            }

            sb.AppendLine("}");

            File.WriteAllText(ENUM_SCRIPT_PATH, sb.ToString());
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog("Success",
                $"PoolName enum generated at:\n{ENUM_SCRIPT_PATH}\n\nTotal pools: {manager.poolDataList.Count}",
                "OK");

            Debug.Log($"[ObjectPoolEditor] Generated PoolName enum at: {ENUM_SCRIPT_PATH}");
        }

        private string SanitizeEnumName(string name)
        {
            StringBuilder sb = new StringBuilder();

            if (char.IsDigit(name[0]))
                sb.Append("Pool_");

            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else if (c == ' ' || c == '-')
                    sb.Append('_');
            }

            return sb.ToString();
        }
    }
}
